### ISSUE TITLE
Suggestion: `make list`

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/nubo#3]
Maybe it would be great to have a command `make list` to know which libraries are available.

**Comment by gabrielhdt** [comment]
What would be the format, in your opinion? A flat list of library paths like
```
libraries/arith_fermat/sttfa,1.0
foo/bar/baz,1.2.3
...
```

**Comment by francoisthire** [comment]
This is fine as a first approximation. 

I was wondering whether we could have

```
make libraries/arith_fermat/sttfa,1.0
```

too which does the `cd <path> ; make ; cd ..` for us.

**Comment by gabrielhdt** [comment]
An ad-hoc solution would be
```
list:
    find . -name infrastructure -prune -o \( -name 'Makefile -print \)' | egrep '/.*/.*/.*/`
```
directly at the root makefile. The other would be to have a recursive `list` target and profit from the `SUBDIR` var.

**Comment by gabrielhdt** [comment]
The recursive list target has been added in 0d31aba8115563a927fd6fa4779f2e3698ca281f, now you can
```sh
make list
```
to obtain
```
encodings/sttfa/1.0
encodings/leibniz/sttfa,1.0
encodings/stte/u,1.0
encodings/stte/sttfa,1.0
encodings/zenon/1.0
encodings/u/1.0
encodings/stte_hole_axioms/u,1.0
encodings/stte_hole_axioms/sttfa,1.0
libraries/iProverModulo/1.0
libraries/isabelle_base/1.0
libraries/isabelle_dk_import/1.0
libraries/hollight_stdlib/u,1.0
libraries/hollight_stdlib/sttfa,1.0
libraries/arith_fermat/sttfa,1.0
libraries/focalide/1.0
libraries/verine/1.0
libraries/isabelle_export/1.0
```
```

**Comment by francoisthire** [comment]
Thanks!
